USE ESHOP;

#INSERT INTO address (COUNTRY,SITY,STREET,BUILDING,ROOM)
#VALUES ('UKRAINE','KUIV','GETMANA', 13, 105);
#INSERT INTO address (COUNTRY,SITY,STREET,BUILDING,ROOM)
#VALUES ('USA','BOSTON','VICTORIAN', 86, 5);
#INSERT INTO address (COUNTRY,SITY,STREET,BUILDING,ROOM)
#VALUES ('GERMANY','BERLIN','GETTE', 26, 44);

#INSERT INTO categories (NAME)
#VALUES ('BOOKS');
#INSERT INTO categories (NAME)
#VALUES ('PHONES');
#INSERT INTO categories (NAME)
#VALUES ('SMARTPHONES');
#INSERT INTO categories (NAME)
#VALUES ('HISTORICAL');

INSERT INTO category_hierarchy 
VALUES ();