-- DROP DATABASE eshop IF EXISTS;

CREATE DATABASE ESHOP;

USE ESHOP;

CREATE TABLE ADDRESS(
ID INT UNIQUE NOT NULL AUTO_INCREMENT,
COUNTRY VARCHAR(32) DEFAULT 'UKRAINE',
CITY VARCHAR(32) DEFAULT 'KUIV',
STREET VARCHAR(32) NOT NULL,
BUILDING VARCHAR(32) NOT NULL,
ROOM VARCHAR(32) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIES(
ID INT UNIQUE NOT NULL AUTO_INCREMENT,
NAME VARCHAR(64) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE CATEGORY_HIERARCHY(
ROOT_ID INT NOT NULL,
CHILD_ID INT NOT NULL,
FOREIGN KEY (ROOT_ID) REFERENCES CATEGORIES (ID),
FOREIGN KEY (CHILD_ID) REFERENCES CATEGORIES (ID)
);

CREATE TABLE USER_TYPE(
ID INT UNIQUE NOT NULL AUTO_INCREMENT,
NAME VARCHAR(16) NOT NULL,
PRIMARY KEY (ID)
);

INSERT INTO USER_TYPE (NAME) VALUE ('CUSTOMER');
INSERT INTO USER_TYPE (NAME) VALUE ('EDITOR');
INSERT INTO USER_TYPE (NAME) VALUE ('ADMIN');

CREATE TABLE USERS(
NAME VARCHAR(16),
LOGIN VARCHAR(32) NOT NULL UNIQUE,
PASSWORD VARCHAR(32) NOT NULL,
EMAIL VARCHAR(32) NOT NULL UNIQUE,
PHONE VARCHAR(16) NOT NULL,
USER_TYPE INT NOT NULL,
ADDRESS INT,
PRIMARY KEY (LOGIN),
FOREIGN KEY (USER_TYPE) REFERENCES USER_TYPE (ID),
FOREIGN KEY (ADDRESS) REFERENCES ADDRESS (ID)
);

CREATE TABLE PRODUCTS(
ID INT UNIQUE NOT NULL AUTO_INCREMENT,
NAME VARCHAR(16) NOT NULL,
PRICE INT UNSIGNED NOT NULL,
MARK TINYINT UNSIGNED,
DESCRIPTION VARCHAR(255),
CATEGORY INT,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORY) REFERENCES CATEGORIES (ID)
);

CREATE TABLE ORDERS(
ID INT UNIQUE NOT NULL AUTO_INCREMENT,
PRICE INT UNSIGNED NOT NULL,
DELIVERY_DATE DATE,
USER VARCHAR(32) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (USER) REFERENCES USERS (LOGIN)
);

CREATE TABLE ORDER_PRODUCTS(
PRODUCT_ID INT UNIQUE NOT NULL,
COUNT INT NOT NULL,
PRICE INT NOT NULL,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID) 
);